"""Added StudentClassroom table

Revision ID: 372e6f8fd521
Revises: 3990d0e97fed
Create Date: 2025-02-21 14:33:06.772571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372e6f8fd521'
down_revision = '3990d0e97fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_classroom')
    # ### end Alembic commands ###
