"""Added Classroom table

Revision ID: 3990d0e97fed
Revises: 3393ecc251d0
Create Date: 2025-02-21 13:58:31.730284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3990d0e97fed'
down_revision = '3393ecc251d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom')
    # ### end Alembic commands ###
